### ISSUE TITLE
python-3 issues

### ISSUE THREAD

**Issue by damonge** [simonsobs/PSpipe#65]
In order to install pspy and make it work with python3 I had to:

1. change `ConfigParser` to `configparser` in so_config.py
2. put parentheses around a bunch of `print` statements in so_dict.py
3. change `except ImportError, exc:` into `except ImportError, exc:` in so_mpi.py

I can open a PR with these if useful

**Comment by damonge** [comment]
Also, when running `python setup.py install --user` at NERSC, not all the files seem to get installed where they should:

- I need to move the mcm module (called `mcm_fortran.cpython-36m-x86_64-linux-gnu.so` in my case) into the installation folder by hand.
- Then I'll get an error that it cannot find `/python/installation/directory/site-packages/pspy-0.0.1-py3.6.egg/pspy/../data/Planck_Parchment_RGB.txt`. Which makes sense because it doesn't get installed there. The file can be found in the root directory, and there's no `data` directory, so I had to create it by hand and then move the file there.

**Comment by thibautlouis** [comment]
Thanks David for the report ! your first comment is fully implemented and we are now looking at the second one !

**Comment by thibautlouis** [comment]
I also fixed the setup.py to answer your second comment, now the installation is much simplier
