### ISSUE TITLE
mpi4py with docker

### ISSUE THREAD

**Issue by josquin-e** [simonsobs/PSpipe#74]
FYI, pip installing mpi4py in the docker environment doesn't seem to be possible.

**Comment by xgarrido** [comment]
Sorry for the late answer. I think this is due to the lack of openmpi library. I will add it.

**Comment by xgarrido** [comment]
Actually, the lateste version of PSpipe docker image embeds MPI library as well as `mpi4py`. `docker pull simonsobs/pspipe` is enough to grab the latest version.
